const types = {
  START_CREATE_TASK: 'START_CREATE_TASK',
  SUCCESS_CREATE_TASK: 'SUCCESS_CREATE_TASK',
  ERROR_CREATE_TASK: 'ERROR_CREATE_TASK',
  START_REGISTER: 'START_REGISTER',
  // ----------Loader----------------------------

  APP_FETCHING_START: 'APP_FETCHING_START',
  APP_FETCHING_SUCCESS: ' APP_FETCHING_SUCCESS',
};
export default types;
