const types = {
  START_REGISTER: 'START_REGISTER',
  SUCCESS_REGISTER: 'SUCCESS_REGISTER',
  ERROR_REGISTER: 'ERROR_REGISTER',

  START_LOGIN: 'START_LOGIN',
  SUCCESS_LOGIN: 'SUCCESS_LOGIN',
  ERROR_LOGIN: 'ERROR_LOGIN',

  START_LOGOUT: 'START_LOGOUT',
  SUCCESS_LOGOUT: 'SUCCESS_LOGOUT',
  ERROR_LOGOUT: 'ERROR_LOGOUT',

  START_REFRESH_USER: 'START_REFRESH_USER',
  SUCCESS_REFRESH_USER: 'SUCCESS_REFRESH_USER',
  ERROR_REFRESH_USER: 'ERROR_REFRESH_USER',

  // ----------Loader----------------------------
  APP_FETCHING_START: 'APP_FETCHING_START',
  APP_FETCHING_SUCCESS: ' APP_FETCHING_SUCCESS',

  // awards
  ADD_AWARDS: 'ADD_AWARDS',
};

export default types;
