const types = {
  START_REGISTER: 'START_REGISTER',
  SUCCESS_REGISTER: 'SUCCESS_REGISTER',
  ERROR_REGISTER: 'ERROR_REGISTER',

  START_LOGIN: 'START_LOGIN',
  SUCCESS_LOGIN: 'SUCCESS_LOGIN',
  ERROR_LOGIN: 'ERROR_LOGIN',

  START_LOGOUT: 'START_LOGOUT',
  SUCCESS_LOGOUT: 'SUCCESS_LOGOUT',
  ERROR_LOGOUT: 'ERROR_LOGOUT',

  START_REFRESH_USER: 'START_REFRESH_USER',
  SUCCESS_REFRESH_USER: 'SUCCESS_REFRESH_USER',
  ERROR_REFRESH_USER: 'ERROR_REFRESH_USER',

  // ----------Loader----------------------------
  LOADER_START: 'LOADER_START',
  LOADER__STOP: 'LOADER__STOP',

  // -----------NewTaskModal------------------
  NEW_TASK_MODAL_OPEN: 'NEW_TASK_MODAL_OPEN',
  NEW_TASK_MODAL_CLOSED: 'NEW_TASK_MODAL_CLOSED',

  // ----------ModalCongrats-----------------
  MODAL_CONGRATS_OPEN: 'MODAL_CONGRATS_OPEN',
  MODAL_CONGRATS_CLOSED: ' MODAL_CONGRATS_CLOSED',

  // ----------ModalLogout-------------------
  MODAL_LOGOUT_OPEN: 'MODAL_LOGOUT_OPEN',
  MODAL_LOGOUT_CLOSED: 'MODAL_LOGOUT_CLOSED',
};

export default types;
